CREATE TABLE usuarios (
  id SERIAL PRIMARY KEY, nombre VARCHAR(100) NOT NULL, correo VARCHAR(150) NOT NULL UNIQUE,
  contrasena_hash VARCHAR(255) NOT NULL, creado_en TIMESTAMP NOT NULL DEFAULT NOW());
CREATE TABLE sesiones (
  id SERIAL PRIMARY KEY, token VARCHAR(255) NOT NULL UNIQUE,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  creado_en TIMESTAMP NOT NULL DEFAULT NOW(), expira_en TIMESTAMP NOT NULL);
CREATE TABLE recuperaciones (
  id SERIAL PRIMARY KEY, usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  codigo CHAR(6) NOT NULL, creado_en TIMESTAMP NOT NULL DEFAULT NOW(),
  expira_en TIMESTAMP NOT NULL, usado BOOLEAN NOT NULL DEFAULT FALSE);
